/* ============================================================
   Fetch latest LONG YouTube uploads for the MDWNH channel and write
   assets/youtube-data.js. No API key, no cookies.

   Strategy:
   1. Resolve the @handle → channelId + real channel name + avatar
      from the public channel page.
   2. Read the public RSS feed (no key) for the latest uploads.
   3. Drop Shorts (only keep long-form videos).
   4. Write the newest 6 to a JS file the site loads.

   Failure policy: if anything goes wrong OR we get 0 videos, we DO NOT
   overwrite the existing file — the last good data stays live.
   ============================================================ */

import { readFileSync, writeFileSync } from 'node:fs';

const HANDLE = 'Mdwn.c';                 // youtube.com/@Mdwn.c
const OUT = 'assets/youtube-data.js';
const MAX = 6;
const FALLBACK_NAME = 'مدونة ستوديو';
const FALLBACK_LOGO = 'Circle Logo.png';

const UA = { headers: { 'User-Agent': 'Mozilla/5.0 (compatible; MdwnhBot/1.0)' } };

async function fetchChannel(handle) {
    const res = await fetch(`https://www.youtube.com/@${handle}`, UA);
    if (!res.ok) throw new Error(`channel page ${res.status}`);
    const html = await res.text();

    const channelId =
        (html.match(/"channelId":"(UC[\w-]+)"/) || html.match(/channel\/(UC[\w-]+)/) || [])[1];
    if (!channelId) throw new Error('channelId not found');

    const name = (html.match(/<meta property="og:title" content="([^"]+)"/) || [])[1] || FALLBACK_NAME;
    const logo =
        (html.match(/"avatar":\{"thumbnails":\[\{"url":"([^"]+)"/) || [])[1] ||
        (html.match(/<meta property="og:image" content="(https:\/\/yt3[^"]+)"/) || [])[1] ||
        FALLBACK_LOGO;

    return { channelId, name, logo };
}

async function fetchFeed(channelId) {
    const res = await fetch(
        `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`, UA);
    if (!res.ok) throw new Error(`feed ${res.status}`);
    return res.text();
}

function parseEntries(xml) {
    const out = [];
    for (const e of xml.split('<entry>').slice(1)) {
        const id = (e.match(/<yt:videoId>([^<]+)<\/yt:videoId>/) || [])[1];
        if (!id) continue;
        let title = (e.match(/<title>([\s\S]*?)<\/title>/) || [])[1] || '';
        title = title
            .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
            .replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
        const published = (e.match(/<published>([^<]+)<\/published>/) || [])[1] || '';
        out.push({ id, title, published });
    }
    return out;
}

/* A Shorts watch page (youtube.com/shorts/<id>) returns 200 for real Shorts,
   and redirects (3xx) to /watch for normal long videos. */
async function isShort(id) {
    try {
        const r = await fetch(`https://www.youtube.com/shorts/${id}`,
            { ...UA, redirect: 'manual' });
        return r.status === 200;
    } catch {
        return false; // if unsure, keep it
    }
}

function currentCount() {
    try {
        return (readFileSync(OUT, 'utf8').match(/"videoId"/g) || []).length;
    } catch {
        return 0;
    }
}

async function main() {
    const ch = await fetchChannel(HANDLE);
    const xml = await fetchFeed(ch.channelId);
    const entries = parseEntries(xml);

    const videos = [];
    for (const e of entries) {
        if (videos.length >= MAX) break;
        if (await isShort(e.id)) continue; // skip Shorts
        videos.push({
            videoId: e.id,
            title: e.title,
            published: e.published,
            thumbnail: `https://i.ytimg.com/vi/${e.id}/hqdefault.jpg`,
            link: `https://www.youtube.com/watch?v=${e.id}`,
            channelName: ch.name,
            channelLogo: ch.logo
        });
    }

    if (videos.length === 0) {
        console.error('Got 0 long videos — keeping existing file.');
        process.exit(0);
    }

    const banner = '/* AUTO-GENERATED by scripts/fetch-youtube.mjs — do not edit by hand. */\n';
    writeFileSync(OUT, banner + 'window.MDWNH_YT = ' + JSON.stringify(videos, null, 2) + ';\n');
    console.log(`Wrote ${videos.length} long videos (was ${currentCount()}).`);
}

main().catch(err => {
    console.error('YouTube fetch failed, keeping existing file:', err.message);
    process.exit(0); // never fail the workflow → old file stays live
});
