/* ============================================================
   Refresh the numbers in إِنْجَازَاتُنَا and writes
   assets/stats-data.js. No API key, no cookies, no login.

   What is read live
     yt      subscribers, total channel views and the video count, off
             the public @handle page
     disc    نادي المدونة's member count, off the public invite

   What is not
     TikTok serves only the first page of a profile to anyone who is not
     logged in, and Instagram publishes no view count at all, so both
     stay hand entered in v4/js/data.js. This script never touches them,
     and never invents them.

   Failure policy, the same as fetch-youtube.mjs: a source that fails is
   dropped from the output rather than written as a zero, and if nothing
   at all came back the existing file is left alone, so the last good
   numbers stay live.
   ============================================================ */

import { readFileSync, writeFileSync } from 'node:fs';

const HANDLE = 'Mdwn.c';
const INVITE = 'RBtp2JVXm6';
const OUT = 'assets/stats-data.js';

/* YouTube serves the trimmed page to an obvious bot, and the channel totals
   are not on it, so ask the way a browser would. */
const UA = {
    headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
            + ' (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
        'Accept-Language': 'ar,en;q=0.8'
    }
};

/* "1,525,199 مشاهدة" / "37.4 ألف مشترك" → a number, or null if it is a
   rounded figure we cannot turn back into an exact one. */
function digits(text) {
    const m = String(text).match(/[\d,.٫٬٠-٩]+/);
    if (!m) return null;
    const plain = m[0]
        .replace(/[٠-٩]/g, (d) => String(d.charCodeAt(0) - 0x0660))
        .replace(/[,٬]/g, '');
    const n = Number(plain);
    return Number.isFinite(n) ? n : null;
}

async function youtube() {
    /* the totals live on the about page, not the channel's front page */
    const res = await fetch(`https://www.youtube.com/@${HANDLE}/about`, UA);
    if (!res.ok) throw new Error(`about page ${res.status}`);
    const html = await res.text();

    const pick = (key) => (html.match(new RegExp(`"${key}":"([^"]+)"`)) || [])[1];
    const subsText = pick('subscriberCountText');
    const viewsText = pick('viewCountText');
    const videosText = pick('videoCountText');

    const views = digits(viewsText);
    if (!views) throw new Error('no channel view count');

    return {
        ytViews: views,
        /* the subscriber line is rounded on the page ("37.4 ألف"), so keep the
           text as YouTube itself shows it and let the site print that */
        ytSubsText: subsText || null,
        ytVideos: digits(videosText)
    };
}

async function discord() {
    const res = await fetch(`https://discord.com/api/v10/invites/${INVITE}?with_counts=true`, UA);
    if (!res.ok) throw new Error(`invite ${res.status}`);
    const data = await res.json();
    const n = data.approximate_member_count;
    if (!n) throw new Error('no member count');
    return { discMembers: n };
}

const out = {};
for (const [name, job] of [['youtube', youtube], ['discord', discord]]) {
    try {
        Object.assign(out, await job());
        console.log(`ok   ${name}`);
    } catch (err) {
        console.log(`skip ${name}: ${err.message}`);
    }
}

if (!Object.keys(out).length) {
    console.log('nothing came back, leaving the file alone');
    process.exit(0);
}

out.at = new Date().toISOString().slice(0, 10);

const body = `/* AUTO-GENERATED by scripts/fetch-stats.mjs — do not edit by hand.
   The hand entered numbers live in v4/js/data.js; this file only carries
   what can be read off a public page. */
window.MDWNH_STATS = ${JSON.stringify(out, null, 2)};
`;

let before = '';
try {
    before = readFileSync(OUT, 'utf8');
} catch {
    /* first run */
}
if (before.trim() === body.trim()) {
    console.log('unchanged');
} else {
    writeFileSync(OUT, body);
    console.log(`wrote ${OUT}`);
}
